package chatBot

var all_models = []struct {
   ok   bool
   slug string
   url  string
}{
   {slug: "ai21/jamba-large-1.7", ok: false},
   {slug: "ai21/jamba-mini-1.7", ok: false},
   {slug: "anthropic/claude-3.5-haiku-20241022", ok: false},
   {slug: "anthropic/claude-3.5-sonnet", ok: false},
   {slug: "anthropic/claude-3.5-sonnet-20240620", ok: false},
   {slug: "anthropic/claude-3.7-sonnet", ok: false},
   {slug: "anthropic/claude-opus-4", ok: false},
   {slug: "anthropic/claude-opus-4.1", ok: true},
   {slug: "anthropic/claude-sonnet-4", ok: true},
   {slug: "arcee-ai/maestro-reasoning", ok: false},
   {slug: "arcee-ai/spotlight", ok: false},
   {slug: "arcee-ai/virtuoso-large", ok: false},
   {slug: "bytedance/ui-tars-1.5-7b", ok: false},
   {slug: "deepseek/deepseek-chat-v3-0324", ok: false},
   {slug: "deepseek/deepseek-chat-v3.1", ok: false},
   {slug: "deepseek/deepseek-prover-v2", ok: false},
   {slug: "deepseek/deepseek-r1", ok: false},
   {slug: "deepseek/deepseek-r1-0528", ok: false},
   {slug: "deepseek/deepseek-r1-distill-llama-70b", ok: false},
   {slug: "deepseek/deepseek-r1-distill-qwen-1.5b", ok: false},
   {slug: "deepseek/deepseek-r1-distill-qwen-32b", ok: false},
   {slug: "deepseek/deepseek-v3-base", ok: false},
   {slug: "deepseek/deepseek-v3.1-base", ok: false},
   {slug: "google/gemini-2.0-flash-001", ok: false},
   {slug: "google/gemini-2.0-flash-lite-001", ok: false},
   {slug: "google/gemini-2.5-flash", ok: true},
   {slug: "google/gemini-2.5-flash-lite", ok: true, url: "https://aistudio.google.com?model=gemini-2.5-flash-lite"},
   {slug: "google/gemini-2.5-flash-lite-preview-06-17", ok: false},
   {slug: "google/gemini-2.5-pro", ok: true},
   {slug: "google/gemini-2.5-pro-exp-03-25", ok: false},
   {slug: "google/gemini-2.5-pro-preview", ok: false},
   {slug: "google/gemini-2.5-pro-preview-05-06", ok: false},
   {slug: "google/gemini-flash-1.5", ok: false},
   {slug: "google/gemini-flash-1.5-8b", ok: false},
   {slug: "google/gemini-pro-1.5", ok: false},
   {slug: "inception/mercury", ok: false},
   {slug: "inception/mercury-coder", ok: false},
   {slug: "meta-llama/llama-4-maverick", ok: false},
   {slug: "meta-llama/llama-4-scout", ok: false},
   {slug: "meta-llama/llama-guard-4-12b", ok: false},
   {slug: "microsoft/mai-ds-r1", ok: false},
   {slug: "minimax/minimax-m1", ok: false},
   {slug: "mistralai/codestral-2508", ok: false},
   {slug: "mistralai/devstral-medium", ok: false},
   {slug: "mistralai/devstral-small", ok: false},
   {slug: "mistralai/devstral-small-2505", ok: false},
   {slug: "mistralai/mistral-medium-3", ok: false},
   {slug: "mistralai/mistral-medium-3.1", ok: false},
   {slug: "mistralai/mistral-small-3.1-24b-instruct", ok: false},
   {slug: "mistralai/mistral-small-3.2-24b-instruct", ok: false},
   {slug: "moonshotai/kimi-vl-a3b-thinking", ok: false},
   {slug: "nvidia/llama-3.1-nemotron-ultra-253b-v1", ok: false},
   {slug: "nvidia/llama-3.3-nemotron-super-49b-v1", ok: false},
   {slug: "openai/codex-mini", ok: false},
   {slug: "openai/gpt-4.1", ok: false},
   {slug: "openai/gpt-4.1-mini", ok: false},
   {slug: "openai/gpt-4.1-nano", ok: false},
   {slug: "openai/gpt-4o", ok: false},
   {slug: "openai/gpt-4o-2024-05-13", ok: false},
   {slug: "openai/gpt-4o-2024-08-06", ok: false},
   {slug: "openai/gpt-4o-2024-11-20", ok: false},
   {slug: "openai/gpt-4o-audio-preview", ok: false},
   {slug: "openai/gpt-4o-mini", ok: false},
   {slug: "openai/gpt-4o-mini-2024-07-18", ok: false},
   {slug: "openai/gpt-4o-mini-search-preview", ok: false},
   {slug: "openai/gpt-4o-search-preview", ok: false},
   {slug: "openai/gpt-5", ok: true, url: "https://platform.openai.com/docs/models/gpt-5"},
   {slug: "openai/gpt-5-chat", ok: true, url: "https://chatgpt.com?model=gpt-5"},
   {slug: "openai/gpt-5-mini", ok: true, url: "https://platform.openai.com/docs/models/gpt-5-mini"},
   {slug: "openai/gpt-5-nano", ok: true, url: "https://platform.openai.com/docs/models/gpt-5-nano"},
   {slug: "openai/gpt-oss-120b", ok: true, url: "https://gpt-oss.com"},
   {slug: "openai/gpt-oss-20b", ok: true, url: "https://gpt-oss.com"},
   {slug: "openai/o3", ok: false},
   {slug: "openai/o3-pro", ok: false},
   {slug: "openai/o4-mini", ok: false},
   {slug: "openai/o4-mini-high", ok: false},
   {slug: "perplexity/r1-1776", ok: false},
   {slug: "perplexity/sonar-deep-research", ok: false},
   {slug: "perplexity/sonar-pro", ok: false},
   {slug: "perplexity/sonar-reasoning-pro", ok: false},
   {slug: "qwen/qwen3-235b-a22b-2507", ok: false},
   {slug: "qwen/qwen3-235b-a22b-thinking-2507", ok: false},
   {slug: "qwen/qwen3-30b-a3b-instruct-2507", ok: false},
   {slug: "qwen/qwen3-8b", ok: false},
   {slug: "qwen/qwen3-coder", ok: true},
   {slug: "qwen/qwq-32b", ok: false},
   {slug: "switchpoint/router", ok: false},
   {slug: "tngtech/deepseek-r1t-chimera", ok: false},
   {slug: "x-ai/grok-3", ok: false},
   {slug: "x-ai/grok-3-beta", ok: false},
   {slug: "x-ai/grok-3-mini", ok: false},
   {slug: "x-ai/grok-3-mini-beta", ok: false},
   {slug: "x-ai/grok-4", ok: false},
   {slug: "z-ai/glm-4-32b", ok: false},
   {slug: "z-ai/glm-4.5", ok: false},
   {slug: "z-ai/glm-4.5-air", ok: false},
}
